"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function Privacy() {
  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Static Background */}
      <div 
        className="fixed inset-0 w-full min-h-screen pointer-events-none"
        style={{
          backgroundImage: 'url(/Day_BG.svg)',
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          zIndex: -1
        }}
      />

      {/* Animated SVG Background - Back layers (moving left) */}
      <div 
        className="fixed inset-0 w-full min-h-screen pointer-events-none cloudLayerBack"
      />
      {/* Animated SVG Background - Front layer (moving right) */}
      <div 
        className="fixed inset-0 w-full min-h-screen pointer-events-none cloudLayerFront"
      />
      
      <style jsx global>{`
        .cloudLayerBack {
          background-image: url(/bg_layer_back.svg);
          background-size: 1206px auto;
          background-repeat: repeat-x;
          background-position: 0 bottom;
          z-index: 0;
          animation: moveLeft 100s linear infinite;
        }
        
        .cloudLayerFront {
          background-image: url(/bg_layer_front.svg);
          background-size: 1206px auto;
          background-repeat: repeat-x;
          background-position: 0 bottom;
          z-index: 1;
          animation: moveRight 120s linear infinite;
        }
        
        @keyframes moveLeft {
          from {
            background-position-x: 0;
          }
          to {
            background-position-x: -1206px;
          }
        }
        
        @keyframes moveRight {
          from {
            background-position-x: 0;
          }
          to {
            background-position-x: 1206px;
          }
        }
      `}</style>

      {/* Navigation */}
      <div className="fixed top-6 left-1/2 -translate-x-1/2 z-50">
        <nav className="flex items-center gap-1 p-1.5 bg-white/80 backdrop-blur-lg border border-white/20 rounded-full shadow-lg shadow-black/5 ring-1 ring-black/5">
          <Link
            href="/"
            className="flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium text-gray-600 hover:text-gray-900 hover:bg-gray-100 transition-all duration-300"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
        </nav>
      </div>

      {/* Content */}
      <div className="relative z-10 pt-32 pb-20 px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="max-w-4xl mx-auto bg-white/60 backdrop-blur-sm rounded-3xl p-8 md:p-12 shadow-sm border border-white/50"
        >
          <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-2">
            Privacy Policy
          </h1>
          <p className="text-gray-500 mb-8">
            Updated at 2025-11-25
          </p>

          <div className="prose prose-gray max-w-none space-y-8 text-gray-600">
            <section>
              <p className="leading-relaxed">
                SNUGL (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by SNUGL.
              </p>
              <p className="leading-relaxed mt-4">
                This Privacy Policy applies to our website, and its associated subdomains (collectively, our &quot;Service&quot;) alongside our application, SNUGL. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Definitions and Key Terms</h2>
              <ul className="list-disc list-inside space-y-2">
                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li><strong>Company:</strong> when this policy mentions &quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our,&quot; it refers to SNUGL, that is responsible for your information under this Privacy Policy.</li>
                <li><strong>Country:</strong> where SNUGL or the owners/founders of SNUGL are based, in this case is Germany.</li>
                <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the SNUGL Service to manage the relationships with your consumers or service users.</li>
                <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit SNUGL and use the services.</li>
                <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information allows for the identification or identifiability of a natural person.</li>
                <li><strong>Service:</strong> refers to the service provided by SNUGL as described in the relative terms and on this platform.</li>
                <li><strong>You:</strong> a person or entity that is registered with SNUGL to use the Services.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">What Information Do We Collect?</h2>
              <p className="leading-relaxed mb-4">We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form:</p>
              <ul className="list-disc list-inside space-y-2">
                <li>Name / Username</li>
                <li>Phone Numbers</li>
                <li>Email Addresses</li>
                <li>Billing Addresses</li>
                <li>Age</li>
              </ul>
              <p className="leading-relaxed mt-4">We also collect information from mobile devices for a better user experience, although these features are completely optional:</p>
              <ul className="list-disc list-inside space-y-2 mt-2">
                <li><strong>Photo Gallery (Pictures):</strong> Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this app.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">How Do We Use The Information We Collect?</h2>
              <p className="leading-relaxed mb-4">Any of the information we collect from you may be used in one of the following ways:</p>
              <ul className="list-disc list-inside space-y-2">
                <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
                <li>To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)</li>
                <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
                <li>To process transactions</li>
                <li>To administer a contest, promotion, survey or other site feature</li>
                <li>To send periodic emails</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Do We Share Information With Third Parties?</h2>
              <p className="leading-relaxed">
                We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners.
              </p>
              <p className="leading-relaxed mt-4">
                We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the app, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the app.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">How Do We Use Your Email Address?</h2>
              <p className="leading-relaxed">
                By submitting your email address on this app, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do.
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
