"use client";

import Image from "next/image";
import Link from "next/link";

export default function Privacy() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      {/* Header */}
      <header className="border-b border-gray-200 dark:border-gray-800">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <Link href="/">
            <Image
              src="/logo.svg"
              alt="SNUGL Logo"
              width={120}
              height={27}
              priority
            />
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
          Privacy Policy
        </h1>
        <p className="text-gray-500 dark:text-gray-400 mb-8">
          Updated at 2025-11-25
        </p>

        <div className="prose prose-gray dark:prose-invert max-w-none space-y-8 text-gray-600 dark:text-gray-300">
          <section>
            <p className="leading-relaxed">
              SNUGL (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by SNUGL.
            </p>
            <p className="leading-relaxed mt-4">
              This Privacy Policy applies to our website, and its associated subdomains (collectively, our &quot;Service&quot;) alongside our application, SNUGL. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Definitions and Key Terms</h2>
            <ul className="list-disc list-inside space-y-2">
              <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
              <li><strong>Company:</strong> when this policy mentions &quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our,&quot; it refers to SNUGL, that is responsible for your information under this Privacy Policy.</li>
              <li><strong>Country:</strong> where SNUGL or the owners/founders of SNUGL are based, in this case is Germany.</li>
              <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the SNUGL Service to manage the relationships with your consumers or service users.</li>
              <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit SNUGL and use the services.</li>
              <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information allows for the identification or identifiability of a natural person.</li>
              <li><strong>Service:</strong> refers to the service provided by SNUGL as described in the relative terms and on this platform.</li>
              <li><strong>You:</strong> a person or entity that is registered with SNUGL to use the Services.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">What Information Do We Collect?</h2>
            <p className="leading-relaxed mb-4">We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>Name / Username</li>
              <li>Phone Numbers</li>
              <li>Email Addresses</li>
              <li>Billing Addresses</li>
              <li>Age</li>
            </ul>
            <p className="leading-relaxed mt-4">We also collect information from mobile devices for a better user experience, although these features are completely optional:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li><strong>Photo Gallery (Pictures):</strong> Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this app.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">How Do We Use The Information We Collect?</h2>
            <p className="leading-relaxed mb-4">Any of the information we collect from you may be used in one of the following ways:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
              <li>To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)</li>
              <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
              <li>To process transactions</li>
              <li>To administer a contest, promotion, survey or other site feature</li>
              <li>To send periodic emails</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Do We Share Information With Third Parties?</h2>
            <p className="leading-relaxed">
              We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners.
            </p>
            <p className="leading-relaxed mt-4">
              We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the app, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the app.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">How Do We Use Your Email Address?</h2>
            <p className="leading-relaxed">
              By submitting your email address on this app, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">How Long Do We Keep Your Information?</h2>
            <p className="leading-relaxed">
              We keep your information only so long as we need it to provide SNUGL to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we&apos;ll either remove it from our systems or depersonalize it so that we can&apos;t identify you.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">How Do We Protect Your Information?</h2>
            <p className="leading-relaxed">
              We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Cookies</h2>
            <p className="leading-relaxed">
              SNUGL uses &quot;Cookies&quot; to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the app as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Information about General Data Protection Regulation (GDPR)</h2>
            <p className="leading-relaxed">
              We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why this data is collected, and how we maintain this data under protection from being replicated or used in the wrong way.
            </p>
            <p className="leading-relaxed mt-4">
              GDPR is an EU-wide privacy and data protection law that regulates how EU residents&apos; data is protected by companies and enhances the control the EU residents have over their personal data. The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Your Data Protection Rights</h2>
            <p className="leading-relaxed mb-4">The Data Protection Principles include requirements such as:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</li>
              <li>Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose.</li>
              <li>Personal data should be held no longer than necessary to fulfil its purpose.</li>
              <li>People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Individual Data Subject&apos;s Rights</h2>
            <p className="leading-relaxed">
              We are committed to helping our customers meet the data subject rights requirements of GDPR. SNUGL processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">California Residents</h2>
            <p className="leading-relaxed mb-4">
              The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it. You may exercise the following rights:
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li><strong>Right to Know and Access:</strong> You may submit a verifiable request for information regarding the categories and specific pieces of Personal Information we have collected about you.</li>
              <li><strong>Right to Equal Service:</strong> We will not discriminate against you if you exercise your privacy rights.</li>
              <li><strong>Right to Delete:</strong> You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</li>
            </ul>
            <p className="leading-relaxed mt-4">We do not sell the Personal Information of our users.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Kids&apos; Privacy</h2>
            <p className="leading-relaxed">
              We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Changes To Our Privacy Policy</h2>
            <p className="leading-relaxed">
              We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Governing Law</h2>
            <p className="leading-relaxed">
              This Privacy Policy is governed by the laws of Germany without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Contact Us</h2>
            <p className="leading-relaxed">
              Don&apos;t hesitate to contact us if you have any questions.
            </p>
            <p className="mt-4">
              <strong>Via Email:</strong>{" "}
              <a href="mailto:info@snugled.com" className="text-blue-600 hover:underline">
                info@snugled.com
              </a>
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-100 dark:bg-gray-800 py-6 px-4 mt-12">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
          <Link href="/">
            <Image src="/logo.svg" alt="SNUGL" width={80} height={18} />
          </Link>
          <div className="flex gap-6 text-sm text-gray-600 dark:text-gray-400">
            <Link href="/agb" className="hover:text-gray-900 dark:hover:text-white">Terms</Link>
            <Link href="/datenschutz" className="hover:text-gray-900 dark:hover:text-white">Privacy</Link>
            <Link href="/" className="hover:text-gray-900 dark:hover:text-white">Home</Link>
          </div>
        </div>
        <div className="max-w-4xl mx-auto mt-4 pt-4 border-t border-gray-200 dark:border-gray-700 text-center text-sm text-gray-500">
          © 2025 SNUGL. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
